#!/bin/bash
#
# Copyright (c) 2013 Eugene Zhuk.
# Use of this source code is governed by the MIT license that can be found
# in the LICENSE file.

# Update system.
sudo yum -q clean all
sudo yum -q makecache
sudo yum -q -y update
